#Author: aescanero@disasterproject.com
#Website: www.disasterproject.com
#Version: 0.1

powerdns:
  enabled: true
  service:
    dns:
      type: LoadBalancer
      port: 53
    api:
      type: ClusterIP
      port: 8081
  image:
    repository: pschiffe/pdns-mysql
    tag: alpine
    pullPolicy: IfNotPresent
  domain: external.local
  master: "yes"
  api: "yes"
  webserver: "yes"
  webserver_address: "0.0.0.0"
  webserver_allow_from: "0.0.0.0/0"
  version_string: "anonymous"
  default_ttl: "1500"
  soa_minimum_ttl: "1200"
  default_soa_name: "ns1.external.local"
  mysql_host: "127.0.0.1"
  mysql_database: "powerdns"
  mysql_user: "powerdns"

alpinemariadb:
  enabled: true
  image:
    repository: yobasystems/alpine-mariadb
    tag: latest
    pullPolicy: IfNotPresent

powerdnsadmin:
  enabled: true
  service:
    type: LoadBalancer
    port: 9191
  image:
    repository: aescanero/powerdns-admin
    tag: latest
    pullPolicy: IfNotPresent
  proto: "http"
  powerdns_host: "127.0.0.1"
  powerdns_port: "8081"
  mysql_host: "127.0.0.1"
  mysql_database: "powerdns"
  mysql_user: "powerdns"


nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
