{{ if .Values.powerdns.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "powerdns.name" . }}-secrets
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "powerdns.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Component }}"
type: Opaque
data:
  {{ if .Values.pdnsApiKey }}
  PDNS_APIKEY: {{ .Values.pdnsApiKey | b64enc }}
  {{ else }}
  PDNS_APIKEY: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
  {{ if .Values.mysqlPass }}
  MYSQL_PASS: {{ .Values.mysqlPass | b64enc }}
  {{ else }}
  MYSQL_PASS: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
  {{ if .Values.pdnsadminSecret }}
  PDNSADMIN_SECRET: {{ .Values.pdnsadminSecret | b64enc }}
  {{ else }}
  PDNSADMIN_SECRET: {{ randAlphaNum 24 | b64enc }}
  {{ end }}
{{ end }}
